### YamlMime:ManagedReference
items:
- uid: Falcon.Application.Abstractions.Endpoints
  commentId: N:Falcon.Application.Abstractions.Endpoints
  id: Falcon.Application.Abstractions.Endpoints
  children:
  - Falcon.Application.Abstractions.Endpoints.EndpointOptions
  langs:
  - csharp
  - vb
  name: Falcon.Application.Abstractions.Endpoints
  nameWithType: Falcon.Application.Abstractions.Endpoints
  fullName: Falcon.Application.Abstractions.Endpoints
  type: Namespace
  assemblies:
  - Falcon.Application.Abstractions
references:
- uid: Falcon.Application.Abstractions.Endpoints.EndpointOptions
  commentId: T:Falcon.Application.Abstractions.Endpoints.EndpointOptions
  href: Falcon.Application.Abstractions.Endpoints.EndpointOptions.html
  name: EndpointOptions
  nameWithType: EndpointOptions
  fullName: Falcon.Application.Abstractions.Endpoints.EndpointOptions
