### YamlMime:ManagedReference
items:
- uid: Falcon.Application.Abstractions.IEndpoints
  commentId: T:Falcon.Application.Abstractions.IEndpoints
  id: IEndpoints
  parent: Falcon.Application.Abstractions
  children:
  - Falcon.Application.Abstractions.IEndpoints.MapApis(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder)
  langs:
  - csharp
  - vb
  name: IEndpoints
  nameWithType: IEndpoints
  fullName: Falcon.Application.Abstractions.IEndpoints
  type: Interface
  source:
    remote:
      path: src/Application/Abstractions/Endpoints/IEndpoints.cs
      branch: feature/development
      repo: https://github.com/natarajanganapathi/Falcon.git
    id: IEndpoints
    path: ../src/Application/Abstractions/Endpoints/IEndpoints.cs
    startLine: 2
  assemblies:
  - Falcon.Application.Abstractions
  namespace: Falcon.Application.Abstractions
  syntax:
    content: public interface IEndpoints
    content.vb: Public Interface IEndpoints
  extensionMethods:
  - Falcon.Application.Abstractions.IEndpoints.Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForCreate``2({TId},System.DateTime)
  - Falcon.Application.Abstractions.IEndpoints.Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForUpdate``2({TId},System.DateTime)
- uid: Falcon.Application.Abstractions.IEndpoints.MapApis(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder)
  commentId: M:Falcon.Application.Abstractions.IEndpoints.MapApis(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder)
  id: MapApis(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder)
  parent: Falcon.Application.Abstractions.IEndpoints
  langs:
  - csharp
  - vb
  name: MapApis(IEndpointRouteBuilder)
  nameWithType: IEndpoints.MapApis(IEndpointRouteBuilder)
  fullName: Falcon.Application.Abstractions.IEndpoints.MapApis(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder)
  type: Method
  source:
    remote:
      path: src/Application/Abstractions/Endpoints/IEndpoints.cs
      branch: feature/development
      repo: https://github.com/natarajanganapathi/Falcon.git
    id: MapApis
    path: ../src/Application/Abstractions/Endpoints/IEndpoints.cs
    startLine: 4
  assemblies:
  - Falcon.Application.Abstractions
  namespace: Falcon.Application.Abstractions
  syntax:
    content: IEndpointRouteBuilder MapApis(IEndpointRouteBuilder route)
    parameters:
    - id: route
      type: Microsoft.AspNetCore.Routing.IEndpointRouteBuilder
    return:
      type: Microsoft.AspNetCore.Routing.IEndpointRouteBuilder
    content.vb: Function MapApis(route As IEndpointRouteBuilder) As IEndpointRouteBuilder
  overload: Falcon.Application.Abstractions.IEndpoints.MapApis*
references:
- uid: Falcon.Application.Abstractions
  commentId: N:Falcon.Application.Abstractions
  href: Falcon.html
  name: Falcon.Application.Abstractions
  nameWithType: Falcon.Application.Abstractions
  fullName: Falcon.Application.Abstractions
  spec.csharp:
  - uid: Falcon
    name: Falcon
    href: Falcon.html
  - name: .
  - uid: Falcon.Application
    name: Application
    href: Falcon.Application.html
  - name: .
  - uid: Falcon.Application.Abstractions
    name: Abstractions
    href: Falcon.Application.Abstractions.html
  spec.vb:
  - uid: Falcon
    name: Falcon
    href: Falcon.html
  - name: .
  - uid: Falcon.Application
    name: Application
    href: Falcon.Application.html
  - name: .
  - uid: Falcon.Application.Abstractions
    name: Abstractions
    href: Falcon.Application.Abstractions.html
- uid: Falcon.Application.Abstractions.IEndpoints.Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForCreate``2({TId},System.DateTime)
  commentId: M:Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForCreate``2(``1,``0,System.DateTime)
  parent: Falcon.Infrastructure.Abstractions.EntityAuditExtentions
  definition: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForCreate``2(``1,``0,System.DateTime)
  href: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.html#Falcon_Infrastructure_Abstractions_EntityAuditExtentions_AuditForCreate__2___1___0_System_DateTime_
  name: AuditForCreate<TId, IEndpoints>(IEndpoints, TId, DateTime)
  nameWithType: EntityAuditExtentions.AuditForCreate<TId, IEndpoints>(IEndpoints, TId, DateTime)
  fullName: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForCreate<TId, Falcon.Application.Abstractions.IEndpoints>(Falcon.Application.Abstractions.IEndpoints, TId, System.DateTime)
  nameWithType.vb: EntityAuditExtentions.AuditForCreate(Of TId, IEndpoints)(IEndpoints, TId, Date)
  fullName.vb: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForCreate(Of TId, Falcon.Application.Abstractions.IEndpoints)(Falcon.Application.Abstractions.IEndpoints, TId, Date)
  name.vb: AuditForCreate(Of TId, IEndpoints)(IEndpoints, TId, Date)
  spec.csharp:
  - uid: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForCreate``2(Falcon.Application.Abstractions.IEndpoints,``0,System.DateTime)
    name: AuditForCreate
    href: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.html#Falcon_Infrastructure_Abstractions_EntityAuditExtentions_AuditForCreate__2___1___0_System_DateTime_
  - name: <
  - name: TId
  - name: ','
  - name: " "
  - uid: Falcon.Application.Abstractions.IEndpoints
    name: IEndpoints
    href: Falcon.Application.Abstractions.IEndpoints.html
  - name: '>'
  - name: (
  - uid: Falcon.Application.Abstractions.IEndpoints
    name: IEndpoints
    href: Falcon.Application.Abstractions.IEndpoints.html
  - name: ','
  - name: " "
  - name: TId
  - name: ','
  - name: " "
  - uid: System.DateTime
    name: DateTime
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.datetime
  - name: )
  spec.vb:
  - uid: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForCreate``2(Falcon.Application.Abstractions.IEndpoints,``0,System.DateTime)
    name: AuditForCreate
    href: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.html#Falcon_Infrastructure_Abstractions_EntityAuditExtentions_AuditForCreate__2___1___0_System_DateTime_
  - name: (
  - name: Of
  - name: " "
  - name: TId
  - name: ','
  - name: " "
  - uid: Falcon.Application.Abstractions.IEndpoints
    name: IEndpoints
    href: Falcon.Application.Abstractions.IEndpoints.html
  - name: )
  - name: (
  - uid: Falcon.Application.Abstractions.IEndpoints
    name: IEndpoints
    href: Falcon.Application.Abstractions.IEndpoints.html
  - name: ','
  - name: " "
  - name: TId
  - name: ','
  - name: " "
  - uid: System.DateTime
    name: Date
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.datetime
  - name: )
- uid: Falcon.Application.Abstractions.IEndpoints.Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForUpdate``2({TId},System.DateTime)
  commentId: M:Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForUpdate``2(``1,``0,System.DateTime)
  parent: Falcon.Infrastructure.Abstractions.EntityAuditExtentions
  definition: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForUpdate``2(``1,``0,System.DateTime)
  href: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.html#Falcon_Infrastructure_Abstractions_EntityAuditExtentions_AuditForUpdate__2___1___0_System_DateTime_
  name: AuditForUpdate<TId, IEndpoints>(IEndpoints, TId, DateTime)
  nameWithType: EntityAuditExtentions.AuditForUpdate<TId, IEndpoints>(IEndpoints, TId, DateTime)
  fullName: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForUpdate<TId, Falcon.Application.Abstractions.IEndpoints>(Falcon.Application.Abstractions.IEndpoints, TId, System.DateTime)
  nameWithType.vb: EntityAuditExtentions.AuditForUpdate(Of TId, IEndpoints)(IEndpoints, TId, Date)
  fullName.vb: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForUpdate(Of TId, Falcon.Application.Abstractions.IEndpoints)(Falcon.Application.Abstractions.IEndpoints, TId, Date)
  name.vb: AuditForUpdate(Of TId, IEndpoints)(IEndpoints, TId, Date)
  spec.csharp:
  - uid: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForUpdate``2(Falcon.Application.Abstractions.IEndpoints,``0,System.DateTime)
    name: AuditForUpdate
    href: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.html#Falcon_Infrastructure_Abstractions_EntityAuditExtentions_AuditForUpdate__2___1___0_System_DateTime_
  - name: <
  - name: TId
  - name: ','
  - name: " "
  - uid: Falcon.Application.Abstractions.IEndpoints
    name: IEndpoints
    href: Falcon.Application.Abstractions.IEndpoints.html
  - name: '>'
  - name: (
  - uid: Falcon.Application.Abstractions.IEndpoints
    name: IEndpoints
    href: Falcon.Application.Abstractions.IEndpoints.html
  - name: ','
  - name: " "
  - name: TId
  - name: ','
  - name: " "
  - uid: System.DateTime
    name: DateTime
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.datetime
  - name: )
  spec.vb:
  - uid: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForUpdate``2(Falcon.Application.Abstractions.IEndpoints,``0,System.DateTime)
    name: AuditForUpdate
    href: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.html#Falcon_Infrastructure_Abstractions_EntityAuditExtentions_AuditForUpdate__2___1___0_System_DateTime_
  - name: (
  - name: Of
  - name: " "
  - name: TId
  - name: ','
  - name: " "
  - uid: Falcon.Application.Abstractions.IEndpoints
    name: IEndpoints
    href: Falcon.Application.Abstractions.IEndpoints.html
  - name: )
  - name: (
  - uid: Falcon.Application.Abstractions.IEndpoints
    name: IEndpoints
    href: Falcon.Application.Abstractions.IEndpoints.html
  - name: ','
  - name: " "
  - name: TId
  - name: ','
  - name: " "
  - uid: System.DateTime
    name: Date
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.datetime
  - name: )
- uid: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForCreate``2(``1,``0,System.DateTime)
  commentId: M:Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForCreate``2(``1,``0,System.DateTime)
  isExternal: true
  href: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.html#Falcon_Infrastructure_Abstractions_EntityAuditExtentions_AuditForCreate__2___1___0_System_DateTime_
  name: AuditForCreate<TId, TEntity>(TEntity, TId, DateTime)
  nameWithType: EntityAuditExtentions.AuditForCreate<TId, TEntity>(TEntity, TId, DateTime)
  fullName: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForCreate<TId, TEntity>(TEntity, TId, System.DateTime)
  nameWithType.vb: EntityAuditExtentions.AuditForCreate(Of TId, TEntity)(TEntity, TId, Date)
  fullName.vb: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForCreate(Of TId, TEntity)(TEntity, TId, Date)
  name.vb: AuditForCreate(Of TId, TEntity)(TEntity, TId, Date)
  spec.csharp:
  - uid: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForCreate``2(``1,``0,System.DateTime)
    name: AuditForCreate
    href: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.html#Falcon_Infrastructure_Abstractions_EntityAuditExtentions_AuditForCreate__2___1___0_System_DateTime_
  - name: <
  - name: TId
  - name: ','
  - name: " "
  - name: TEntity
  - name: '>'
  - name: (
  - name: TEntity
  - name: ','
  - name: " "
  - name: TId
  - name: ','
  - name: " "
  - uid: System.DateTime
    name: DateTime
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.datetime
  - name: )
  spec.vb:
  - uid: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForCreate``2(``1,``0,System.DateTime)
    name: AuditForCreate
    href: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.html#Falcon_Infrastructure_Abstractions_EntityAuditExtentions_AuditForCreate__2___1___0_System_DateTime_
  - name: (
  - name: Of
  - name: " "
  - name: TId
  - name: ','
  - name: " "
  - name: TEntity
  - name: )
  - name: (
  - name: TEntity
  - name: ','
  - name: " "
  - name: TId
  - name: ','
  - name: " "
  - uid: System.DateTime
    name: Date
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.datetime
  - name: )
- uid: Falcon.Infrastructure.Abstractions.EntityAuditExtentions
  commentId: T:Falcon.Infrastructure.Abstractions.EntityAuditExtentions
  parent: Falcon.Infrastructure.Abstractions
  href: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.html
  name: EntityAuditExtentions
  nameWithType: EntityAuditExtentions
  fullName: Falcon.Infrastructure.Abstractions.EntityAuditExtentions
- uid: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForUpdate``2(``1,``0,System.DateTime)
  commentId: M:Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForUpdate``2(``1,``0,System.DateTime)
  isExternal: true
  href: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.html#Falcon_Infrastructure_Abstractions_EntityAuditExtentions_AuditForUpdate__2___1___0_System_DateTime_
  name: AuditForUpdate<TId, TEntity>(TEntity, TId, DateTime)
  nameWithType: EntityAuditExtentions.AuditForUpdate<TId, TEntity>(TEntity, TId, DateTime)
  fullName: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForUpdate<TId, TEntity>(TEntity, TId, System.DateTime)
  nameWithType.vb: EntityAuditExtentions.AuditForUpdate(Of TId, TEntity)(TEntity, TId, Date)
  fullName.vb: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForUpdate(Of TId, TEntity)(TEntity, TId, Date)
  name.vb: AuditForUpdate(Of TId, TEntity)(TEntity, TId, Date)
  spec.csharp:
  - uid: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForUpdate``2(``1,``0,System.DateTime)
    name: AuditForUpdate
    href: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.html#Falcon_Infrastructure_Abstractions_EntityAuditExtentions_AuditForUpdate__2___1___0_System_DateTime_
  - name: <
  - name: TId
  - name: ','
  - name: " "
  - name: TEntity
  - name: '>'
  - name: (
  - name: TEntity
  - name: ','
  - name: " "
  - name: TId
  - name: ','
  - name: " "
  - uid: System.DateTime
    name: DateTime
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.datetime
  - name: )
  spec.vb:
  - uid: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.AuditForUpdate``2(``1,``0,System.DateTime)
    name: AuditForUpdate
    href: Falcon.Infrastructure.Abstractions.EntityAuditExtentions.html#Falcon_Infrastructure_Abstractions_EntityAuditExtentions_AuditForUpdate__2___1___0_System_DateTime_
  - name: (
  - name: Of
  - name: " "
  - name: TId
  - name: ','
  - name: " "
  - name: TEntity
  - name: )
  - name: (
  - name: TEntity
  - name: ','
  - name: " "
  - name: TId
  - name: ','
  - name: " "
  - uid: System.DateTime
    name: Date
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.datetime
  - name: )
- uid: Falcon.Infrastructure.Abstractions
  commentId: N:Falcon.Infrastructure.Abstractions
  href: Falcon.html
  name: Falcon.Infrastructure.Abstractions
  nameWithType: Falcon.Infrastructure.Abstractions
  fullName: Falcon.Infrastructure.Abstractions
  spec.csharp:
  - uid: Falcon
    name: Falcon
    href: Falcon.html
  - name: .
  - uid: Falcon.Infrastructure
    name: Infrastructure
    href: Falcon.Infrastructure.html
  - name: .
  - uid: Falcon.Infrastructure.Abstractions
    name: Abstractions
    href: Falcon.Infrastructure.Abstractions.html
  spec.vb:
  - uid: Falcon
    name: Falcon
    href: Falcon.html
  - name: .
  - uid: Falcon.Infrastructure
    name: Infrastructure
    href: Falcon.Infrastructure.html
  - name: .
  - uid: Falcon.Infrastructure.Abstractions
    name: Abstractions
    href: Falcon.Infrastructure.Abstractions.html
- uid: Falcon.Application.Abstractions.IEndpoints.MapApis*
  commentId: Overload:Falcon.Application.Abstractions.IEndpoints.MapApis
  href: Falcon.Application.Abstractions.IEndpoints.html#Falcon_Application_Abstractions_IEndpoints_MapApis_Microsoft_AspNetCore_Routing_IEndpointRouteBuilder_
  name: MapApis
  nameWithType: IEndpoints.MapApis
  fullName: Falcon.Application.Abstractions.IEndpoints.MapApis
- uid: Microsoft.AspNetCore.Routing.IEndpointRouteBuilder
  commentId: T:Microsoft.AspNetCore.Routing.IEndpointRouteBuilder
  parent: Microsoft.AspNetCore.Routing
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.routing.iendpointroutebuilder
  name: IEndpointRouteBuilder
  nameWithType: IEndpointRouteBuilder
  fullName: Microsoft.AspNetCore.Routing.IEndpointRouteBuilder
- uid: Microsoft.AspNetCore.Routing
  commentId: N:Microsoft.AspNetCore.Routing
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.AspNetCore.Routing
  nameWithType: Microsoft.AspNetCore.Routing
  fullName: Microsoft.AspNetCore.Routing
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.AspNetCore
    name: AspNetCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore
  - name: .
  - uid: Microsoft.AspNetCore.Routing
    name: Routing
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.routing
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.AspNetCore
    name: AspNetCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore
  - name: .
  - uid: Microsoft.AspNetCore.Routing
    name: Routing
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.routing
