### YamlMime:ManagedReference
items:
- uid: Falcon.Application.Abstractions.Infrastructure.Services
  commentId: N:Falcon.Application.Abstractions.Infrastructure.Services
  id: Falcon.Application.Abstractions.Infrastructure.Services
  children:
  - Falcon.Application.Abstractions.Infrastructure.Services.IIdentityService
  - Falcon.Application.Abstractions.Infrastructure.Services.IdentityService
  langs:
  - csharp
  - vb
  name: Falcon.Application.Abstractions.Infrastructure.Services
  nameWithType: Falcon.Application.Abstractions.Infrastructure.Services
  fullName: Falcon.Application.Abstractions.Infrastructure.Services
  type: Namespace
  assemblies:
  - Falcon.Application.Abstractions
references:
- uid: Falcon.Application.Abstractions.Infrastructure.Services.IdentityService
  commentId: T:Falcon.Application.Abstractions.Infrastructure.Services.IdentityService
  href: Falcon.Application.Abstractions.Infrastructure.Services.IdentityService.html
  name: IdentityService
  nameWithType: IdentityService
  fullName: Falcon.Application.Abstractions.Infrastructure.Services.IdentityService
- uid: Falcon.Application.Abstractions.Infrastructure.Services.IIdentityService
  commentId: T:Falcon.Application.Abstractions.Infrastructure.Services.IIdentityService
  parent: Falcon.Application.Abstractions.Infrastructure.Services
  href: Falcon.Application.Abstractions.Infrastructure.Services.IIdentityService.html
  name: IIdentityService
  nameWithType: IIdentityService
  fullName: Falcon.Application.Abstractions.Infrastructure.Services.IIdentityService
- uid: Falcon.Application.Abstractions.Infrastructure.Services
  commentId: N:Falcon.Application.Abstractions.Infrastructure.Services
  href: Falcon.html
  name: Falcon.Application.Abstractions.Infrastructure.Services
  nameWithType: Falcon.Application.Abstractions.Infrastructure.Services
  fullName: Falcon.Application.Abstractions.Infrastructure.Services
  spec.csharp:
  - uid: Falcon
    name: Falcon
    href: Falcon.html
  - name: .
  - uid: Falcon.Application
    name: Application
    href: Falcon.Application.html
  - name: .
  - uid: Falcon.Application.Abstractions
    name: Abstractions
    href: Falcon.Application.Abstractions.html
  - name: .
  - uid: Falcon.Application.Abstractions.Infrastructure
    name: Infrastructure
    href: Falcon.Application.Abstractions.Infrastructure.html
  - name: .
  - uid: Falcon.Application.Abstractions.Infrastructure.Services
    name: Services
    href: Falcon.Application.Abstractions.Infrastructure.Services.html
  spec.vb:
  - uid: Falcon
    name: Falcon
    href: Falcon.html
  - name: .
  - uid: Falcon.Application
    name: Application
    href: Falcon.Application.html
  - name: .
  - uid: Falcon.Application.Abstractions
    name: Abstractions
    href: Falcon.Application.Abstractions.html
  - name: .
  - uid: Falcon.Application.Abstractions.Infrastructure
    name: Infrastructure
    href: Falcon.Application.Abstractions.Infrastructure.html
  - name: .
  - uid: Falcon.Application.Abstractions.Infrastructure.Services
    name: Services
    href: Falcon.Application.Abstractions.Infrastructure.Services.html
