name: Falcon Build

on:
  push:
    branches: [ "feature/*" ]
    paths-ignore: ["docfx", "samples", ".github"]
  pull_request:
    branches: [ "main"]
    paths-ignore: ["docfx", "samples", ".github"]
  workflow_dispatch:

env:
  PROJECT: ./Falcon.sln

jobs:
  build:
    name: Build SparkPlug.Api App
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]
            dotnet-version: [9.0.x]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT }}
    - name: Build
      run: dotnet build ${{ env.PROJECT }} --no-restore
